### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by kyhubber** [zoho/zcrm-csharp-sdk#3]
This is an excellent  project. The only easy to use one. Unfortunately it wont install. Error: Could not install package 'baseVISION.Tool.Connectors.Zoho 1.0.7'. You are trying to install this package into a project that targets '.NETFramework,Version=', but the package does not contain any assembly references or content files that are compatible with that framework.
Version doesn't matter have tried all, 2.0 thru 4.6

**Comment by raja-7453** [comment]
```baseVISION.Tool.Connectors.Zoho 1.0.7 ```  SDK is not owned by ZOHO. Use original latest [ZOHO's SDK](https://www.zoho.com/crm/help/developer/csharp-sdk/overview.html)  ```ZCRMSDK --version 1.0.2```. Note that the minimum version of .NETFramework required is 4.6.1.
