### ISSUE TITLE
Picklist values not parsed correctly in BulkData

### ISSUE THREAD

**Issue by jonathanBamboo** [zoho/zcrm-csharp-sdk#8]
Bulkdata is giving me this output (all of them are null).
![image](https://user-images.githubusercontent.com/50717054/57880520-f5b86380-77ec-11e9-8dcb-db172a4414f1.png)

When in reality, the values should match the json:
![image](https://user-images.githubusercontent.com/50717054/57880688-63fd2600-77ed-11e9-9d5a-d0a67e36d9df.png)

**Comment by raja-7453** [comment]
This issue is fixed in ZCRMSDK - version 2.0.2. Please upgrade to version 2.0.2.
